# Generated by Django 5.2.9 on 2026-01-01 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('examTitle', models.CharField(max_length=255)),
                ('durationInSec', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('totalMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics')], max_length=11)),
                ('subjImage', models.ImageField(blank=True, null=True, upload_to='practice_subject_images/')),
                ('durationInMin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('questionType', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('NUM', 'NUMERICAL')], max_length=3)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=6)),
                ('refImage', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('category', models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2')], max_length=100, null=True)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.exam')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.practice')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('optionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('identifier', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcq_correct_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('numerical_answer', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('numerical_answer_range_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('numerical_answer_range_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sectionTitle', models.CharField(max_length=255)),
                ('numberOfQuestions', models.IntegerField()),
                ('marksPerQuestion', models.IntegerField()),
                ('exam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.exam')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.section'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('summary', models.TextField()),
                ('estMinutes', models.IntegerField()),
                ('progressPercent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='assessments.practice')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.topic'),
        ),
    ]
