# Generated by Django 5.2.9 on 2026-01-01 21:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('attemptId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='demo_user', max_length=150)),
                ('status', models.CharField(choices=[('in-progress', 'In Progress'), ('incomplete', 'Incomplete'), ('completed', 'Completed')], default='in-progress', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_attempts', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.exam')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.practice')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('statsId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(default='demo_user', max_length=150)),
                ('total_questions', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('marks', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('not_attempted', models.IntegerField(default=0)),
                ('attempt_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('difficulty_wise_stats', models.JSONField(default=dict)),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='performance.examattempt')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('answerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option_identifier', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('numerical_answer', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('answer_status', models.CharField(choices=[('NOT_VISITED', 'Not Visited'), ('ANSWERED', 'Answered'), ('NOT_ANSWERED', 'Not Answered'), ('MARKED_FOR_REVIEW', 'Marked for Review'), ('ANSWERED_AND_MARKED', 'Answered and Marked for Review')], default='not_answered', max_length=20)),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='performance.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
            ],
        ),
    ]
