# Generated by Django 5.2.9 on 2025-12-20 11:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('examId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('examTitle', models.CharField(max_length=255)),
                ('durationInSec', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('totalMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('PHY', 'Physics'), ('CHM', 'Chemistry'), ('MTH', 'Mathematics')], max_length=3)),
                ('subjImage', models.ImageField(blank=True, null=True, upload_to='practice_subject_images/')),
                ('durationInMin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('questionText', models.TextField()),
                ('questionType', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('NUM', 'NUMERICAL')], max_length=3)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('refImage', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.exam')),
                ('practice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.practice')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('optionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('identifier', models.CharField(max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessments.question')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('sectionId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sectionTitle', models.CharField(max_length=255)),
                ('numberOfQuestions', models.IntegerField()),
                ('marksPerQuestion', models.IntegerField()),
                ('exam', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessments.exam')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.section'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topicId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=1)),
                ('summary', models.TextField()),
                ('estMinutes', models.IntegerField()),
                ('progressPercent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='assessments.practice')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.topic'),
        ),
    ]
