# Generated by Django 5.2.9 on 2025-12-20 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerical_answer', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('numerical_answer_range_min', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('numerical_answer_range_max', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('mcq_correct_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.option')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='assessments.question')),
            ],
        ),
    ]
