# Generated by Django 5.2.9 on 2025-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_correctanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctanswer',
            name='mcq_correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True),
        ),
    ]
