# Generated by Django 5.2.9 on 2025-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_option_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(blank=True, choices=[('Level 1', 'Level 1'), ('Level 2', 'Level 2')], max_length=100, null=True),
        ),
    ]
