# Generated by Django 5.2.9 on 2025-12-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_question_marks_alter_question_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Mathematics', 'Mathematics')], max_length=11),
        ),
    ]
