# Generated by Django 5.2.9 on 2025-12-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='is_correct',
        ),
    ]
