# Generated by Django 5.2.9 on 2025-12-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_remove_useranswer_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_status',
            field=models.CharField(choices=[('NOT_VISITED', 'Not Visited'), ('ANSWERED', 'Answered'), ('NOT_ANSWERED', 'Not Answered'), ('MARKED_FOR_REVIEW', 'Marked for Review'), ('ANSWERED_AND_MARKED', 'Answered and Marked for Review')], default='not_answered', max_length=20),
        ),
    ]
