# Generated by Django 5.2.9 on 2025-12-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_useranswer_answer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
