# Generated by Django 5.2.9 on 2025-12-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_stats_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
